# Generated by Django 4.0 on 2022-05-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=60)),
                ('photo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('dealer_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('officename', models.CharField(max_length=60)),
                ('officeaddress', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('dealershipdate', models.CharField(max_length=60)),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('doj', models.CharField(max_length=60)),
                ('qualification', models.CharField(max_length=60)),
                ('department', models.CharField(max_length=60)),
                ('post', models.CharField(max_length=60)),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('did', models.IntegerField()),
                ('sid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('prod_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=80)),
                ('photo', models.CharField(max_length=40)),
                ('unitprice', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('quantity', models.CharField(max_length=60)),
                ('stockquantity', models.CharField(max_length=60)),
                ('remark', models.CharField(max_length=40)),
                ('expiredate', models.CharField(max_length=40)),
                ('manifacturedate', models.CharField(max_length=40)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
