# Generated by Django 4.0 on 2022-05-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealerorder',
            fields=[
                ('order_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('order_date', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('paymentstatus', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dealer')),
            ],
            options={
                'db_table': 'dealerorder',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='stockquantity',
        ),
        migrations.AddField(
            model_name='tbl_idgen',
            name='odid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('payment_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('accnumber', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dealer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dealerorder')),
            ],
            options={
                'db_table': 'tbl_payment',
            },
        ),
        migrations.CreateModel(
            name='tbl_dealerorderdetails',
            fields=[
                ('orderdet_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.CharField(max_length=30)),
                ('remark', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dealerorder')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
            ],
            options={
                'db_table': 'tbl_dealerordersetails',
            },
        ),
    ]
