# Generated by Django 4.0 on 2022-05-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=40)),
                ('cat_name', models.CharField(max_length=60)),
                ('photo', models.CharField(max_length=80)),
            ],
        ),
    ]
