# Generated by Django 4.0 on 2022-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=40)),
                ('cat_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=80)),
                ('photo', models.CharField(max_length=40)),
                ('unitprice', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('quantity', models.CharField(max_length=60)),
                ('stockquantity', models.CharField(max_length=60)),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
    ]
