# Generated by Django 4.0 on 2022-05-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_dealerorder_remove_products_stockquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_dealerorderdetails',
            name='remark',
        ),
    ]
