# Generated by Django 4.0 on 2022-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_tbl_dealerorderdetails_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='orid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_idgen',
            name='p1id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
