# Generated by Django 4.0 on 2022-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('doj', models.CharField(max_length=60)),
                ('qualification', models.CharField(max_length=60)),
                ('department', models.CharField(max_length=60)),
                ('post', models.CharField(max_length=60)),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
    ]
