# Generated by Django 4.0 on 2022-05-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('officename', models.CharField(max_length=60)),
                ('officeaddress', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
    ]
