# Generated by Django 4.0 on 2022-05-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_tbl_dealerorderdetails_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_dealerorderdetails',
            old_name='product_id',
            new_name='prod_id',
        ),
    ]
