# Generated by Django 4.0 on 2022-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealershipdate',
            field=models.CharField(default='f', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.CharField(default='f', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='expiredate',
            field=models.CharField(default='d', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='manifacturedate',
            field=models.CharField(default='d', max_length=40),
            preserve_default=False,
        ),
    ]
