# Generated by Django 4.0.5 on 2022-06-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_tbl_idgen_dlid_tbl_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='cnid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_cancel',
            fields=[
                ('cancel_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cancel_reason', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('cancel_date', models.CharField(max_length=30)),
                ('orderdet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tbl_dealerorderdetails')),
            ],
            options={
                'db_table': 'tbl_cancel',
            },
        ),
    ]
